mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
ipv6: true

experimental:
  ignore-resolve-fail: true
  
unified-delay: false
tcp-concurrent: true                  #【Meta专属】TCP 并发连接所有 IP, 将使用最快握手的 TCP
keep-alive-interval: 30               #  TCP keep alive interval
skip-auth-prefixes:                   # 设置跳过验证的IP段
  - 127.0.0.1/8
  - ::1/128

profile:
  store-selected: true                # 存储 select 选择记录
  store-fake-ip: true                 # 持久化 fake-ip

sniffer:                              # 嗅探域名 可选配置
  enable: true
  parse-pure-ip: true                 # 是否使用嗅探结果作为实际访问，默认 true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS: 
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]


tun:
  enable: true
  stack: system                       # 可选： system/gvisor/
  dns-hijack: [any:53]                # dns劫持,一般设置为 any:53 即可, 即劫持所有53端口的udp流量
  strict-route: true                  # 将所有连接路由到tun来防止泄漏，但你的设备将无法被其他设备访问
  auto-route: true                    # 自动设置全局路由，可以自动将全局流量路由进入tun网卡。
  auto-detect-interface: true         # 自动识别出口网卡

dns:
  enable: true                        # 关闭将使用系统 DNS
  ipv6: false                         # IPV6解析开关；如果为false，将返回ipv6结果为空
  enhanced-mode: fake-ip              # 模式：redir-host或fake-ip
  fake-ip-range: 198.18.0.1/16        # fakeip 下的 IP 段设置，tun 网卡的默认 ip 也使用此值
  fake-ip-filter: ['*', '+.lan', '+.local', '+.msftncsi.com', '+.msftconnecttest.com']
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver: [https://dns.alidns.com/dns-query, https://doh.pub/dns-query]
