mode: rule
ipv6: true
log-level: info
mixed-port: 7897
tcp-concurrent: true
keep-alive-interval: 15
external-controller: 127.0.0.1:53345
find-process-mode: strict
global-client-fingerprint: chrome
dns:
  enable: true
  prefer-h3: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 0.0.0.0:53
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - +.lan
    - +.local
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
  nameserver:
    # - 853.afwfv.cn
    - https://223.6.6.6/dns-query
    - https://doh.360.cn/dns-query
