# The `Merge` format used to enhance profile
allow-lan: true
bind-address: '*'                     # 监听IP白名单，可绑定单个IPv4和v6地址，"*" 为绑定所有IP地址，仅在将allow-lan设置为true时适用
unified-delay: false                  # 统一延迟，更换延迟计算方式，去除握手等额外延迟
tcp-concurrent: true                  #【Meta专属】TCP 并发连接所有 IP, 将使用最快握手的 TCP
keep-alive-interval: 15               #  TCP keep alive interval
profile:
  store-selected: true                # 存储 select 选择记录
  store-fake-ip: true                 # 持久化 fake-ip

dns:
  enable: true                        # 关闭将使用系统 DNS
  ipv6: false                          # IPV6解析开关；如果为false，将返回ipv6结果为空
  enhanced-mode: fake-ip              # 模式：redir-host或fake-ip
  listen: 0.0.0.0:1053                # DNS 监听地
  fake-ip-range: 198.18.0.1/16        # fakeip 下的 IP 段设置，tun 网卡的默认 ip 也使用此值
  fake-ip-filter: ['*', '+.lan', '+.local']
                                      # Fake-ip 过滤，列表中的域名返回真实IP
  nameserver: [223.5.5.5, 119.29.29.29]
                                      # 默认DNS服务器，支持udp/tcp/dot/doh/doq
  fallback: [tls://8.8.4.4, tls://1.0.0.1]
                                      # fallbaack DNS服务器，支持udp/tcp/dot/doh/doq
