# The `Merge` format used to enhance profile
allow-lan: true
bind-address: '*'                     # 监听IP白名单，可绑定单个IPv4和v6地址，"*" 为绑定所有IP地址，仅在将allow-lan设置为true时适用
unified-delay: false                  # 统一延迟，更换延迟计算方式，去除握手等额外延迟
tcp-concurrent: true                  #【Meta专属】TCP 并发连接所有 IP, 将使用最快握手的 TCP
keep-alive-interval: 15               #  TCP keep alive interval
skip-auth-prefixes:                   # 设置跳过验证的IP段
  - 127.0.0.1/8
  - ::1/128
find-process-mode: strict             # 匹配所有进程（always/strict/off）
global-client-fingerprint: chrome     # 全局 TLS 指纹，优先低于 proxy 内的 client-fingerprint
                                      # 可选： "chrome","firefox","safari","ios","random","none" options.
profile:
  store-selected: true                # 存储 select 选择记录
  store-fake-ip: true                 # 持久化 fake-ip

sniffer:                              # 嗅探域名 可选配置
  enable: true
  parse-pure-ip: true                 # 是否使用嗅探结果作为实际访问，默认 true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

dns:
  enable: true                        # 关闭将使用系统 DNS
  ipv6: true                          # IPV6解析开关；如果为false，将返回ipv6结果为空
  enhanced-mode: fake-ip              # 模式：redir-host或fake-ip
  listen: :1053                         # DNS 监听地
  fake-ip-range: 198.18.0.1/16        # fakeip 下的 IP 段设置，tun 网卡的默认 ip 也使用此值
  fake-ip-filter: ['*', '+.lan', '+.local', '+.msftncsi.com', '+.msftconnecttest.com']
                                      # Fake-ip 过滤，列表中的域名返回真实IP
  proxy-server-nameserver: [https://dns.alidns.com/dns-query, https://doh.pub/dns-query]
                                      # 代理DNS服务器，支持udp/tcp/dot/doh/doq
  nameserver-policy:
   "geosite:cn,private": [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
                                      # 指定域名查询的解析服务器，可使用 geosite, 优先于 nameserver/fallback 查询
  nameserver: [223.5.5.5, 119.29.29.29]
                                      # 默认DNS服务器，支持udp/tcp/dot/doh/doq
  fallback: [tls://8.8.4.4, tls://1.1.1.1]
                                      # fallbaack DNS服务器，支持udp/tcp/dot/doh/doq
  fallback-filter: { geoip: true, geoip-code: CN, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
